"""Initial migration

Revision ID: 93ed348210b0
Revises: 
Create Date: 2024-12-02 14:53:14.548376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ed348210b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('data')
        batch_op.drop_column('content_type')
        batch_op.drop_column('filename')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('data')
        batch_op.drop_column('content_type')
        batch_op.drop_column('filename')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
